services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    networks:
      - valid_network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    networks:
      - valid_network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # UI management

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    command: start-dev
    restart: always
    networks:
      - valid_network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  api:
    build:
      context: ./src
      dockerfile: Api/Dockerfile
    container_name: api
    networks:
      - valid_network
    depends_on:
      - postgres
      - rabbitmq
      - keycloak
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=db;Username=db_user;Password=db_pass"
 
  worker:
    build:
      context: ./src
      dockerfile: Worker/Dockerfile
    container_name: worker
    networks:
      - valid_network
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=db;Username=db_user;Password=db_pass"
      Rabbit__Host: rabbitmq

  web:
    build: ./valid-front
    container_name: front
    depends_on:
      - api
      - keycloak
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: "http://localhost:5000"
      VITE_KEYCLOAK_URL: "http://localhost:8080"
      VITE_KEYCLOAK_REALM: "valid"
      VITE_KEYCLOAK_CLIENT_ID: "valid-front"



volumes:
  pgdata:

networks:
  valid_network:
    external: true
